# Generated by Django 4.2.2 on 2023-06-28 23:36

import addons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.BinaryField(max_length=16, verbose_name='uuid')),
                ('type', models.PositiveSmallIntegerField(verbose_name='type')),
            ],
            options={
                'verbose_name': 'Litebans_Allow',
                'verbose_name_plural': 'Litebans_Allow',
            },
        ),
        migrations.CreateModel(
            name='Bans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=None, max_length=36, null=True, verbose_name='uuid')),
                ('ip', models.CharField(default=None, max_length=45, null=True, verbose_name='ip')),
                ('reason', models.CharField(default=None, max_length=2048, null=True, verbose_name='reason')),
                ('banned_by_uuid', models.CharField(max_length=36, verbose_name='banned_by_uuid')),
                ('banned_by_name', models.CharField(default=None, max_length=128, null=True, verbose_name='banned_by_name')),
                ('removed_by_uuid', models.CharField(default=None, max_length=36, null=True, verbose_name='removed_by_uuid')),
                ('removed_by_name', models.CharField(default=None, max_length=128, null=True, verbose_name='removed_by_name')),
                ('removed_by_reason', models.CharField(default=None, max_length=2048, null=True, verbose_name='removed_by_reason')),
                ('removed_by_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='removed_by_date')),
                ('time', models.BigIntegerField(verbose_name='time')),
                ('until', models.BigIntegerField(verbose_name='until')),
                ('template', models.PositiveSmallIntegerField(default=255, verbose_name='template')),
                ('server_scope', models.CharField(default=None, max_length=32, null=True, verbose_name='server_scope')),
                ('server_origin', models.CharField(default=None, max_length=32, null=True, verbose_name='server_origin')),
                ('silent', addons.models.MySQLBooleanField(null=True)),
                ('ipban', addons.models.MySQLBooleanField(null=True)),
                ('ipban_wildcard', addons.models.MySQLBooleanField(default=b'0', null=True)),
                ('active', addons.models.MySQLBooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Litebans_Bans',
                'verbose_name_plural': 'Litebans_Bans',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128, verbose_name='version')),
                ('build', models.CharField(max_length=128, verbose_name='build')),
                ('timezone', models.CharField(default='+00:00', max_length=64, verbose_name='timezone')),
            ],
            options={
                'verbose_name': 'Litebans_Config',
                'verbose_name_plural': 'Litebans_Config',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date')),
                ('name', models.CharField(default=None, max_length=16, null=True, verbose_name='name')),
                ('uuid', models.CharField(default=None, max_length=36, null=True, verbose_name='uuid')),
                ('ip', models.CharField(default=None, max_length=45, null=True, verbose_name='ip')),
            ],
            options={
                'verbose_name': 'Litebans_History',
                'verbose_name_plural': 'Litebans_History',
            },
        ),
        migrations.CreateModel(
            name='Kicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=None, max_length=36, null=True, verbose_name='uuid')),
                ('ip', models.CharField(default=None, max_length=45, null=True, verbose_name='ip')),
                ('reason', models.CharField(default=None, max_length=2048, null=True, verbose_name='reason')),
                ('banned_by_uuid', models.CharField(max_length=36, verbose_name='banned_by_uuid')),
                ('banned_by_name', models.CharField(default=None, max_length=128, null=True, verbose_name='banned_by_name')),
                ('time', models.BigIntegerField(verbose_name='time')),
                ('until', models.BigIntegerField(verbose_name='until')),
                ('template', models.PositiveSmallIntegerField(default=255, verbose_name='template')),
                ('server_scope', models.CharField(default=None, max_length=32, null=True, verbose_name='server_scope')),
                ('server_origin', models.CharField(default=None, max_length=32, null=True, verbose_name='server_origin')),
                ('silent', addons.models.MySQLBooleanField(null=True)),
                ('ipban', addons.models.MySQLBooleanField(null=True)),
                ('ipban_wildcard', addons.models.MySQLBooleanField(default=b'0', null=True)),
                ('active', addons.models.MySQLBooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Litebans_Kicks',
                'verbose_name_plural': 'Litebans_Kicks',
            },
        ),
        migrations.CreateModel(
            name='Mutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=None, max_length=36, null=True, verbose_name='uuid')),
                ('ip', models.CharField(default=None, max_length=45, null=True, verbose_name='ip')),
                ('reason', models.CharField(default=None, max_length=2048, null=True, verbose_name='reason')),
                ('banned_by_uuid', models.CharField(max_length=36, verbose_name='banned_by_uuid')),
                ('banned_by_name', models.CharField(default=None, max_length=128, null=True, verbose_name='banned_by_name')),
                ('removed_by_uuid', models.CharField(default=None, max_length=36, null=True, verbose_name='removed_by_uuid')),
                ('removed_by_name', models.CharField(default=None, max_length=128, null=True, verbose_name='removed_by_name')),
                ('removed_by_reason', models.CharField(default=None, max_length=2048, null=True, verbose_name='removed_by_reason')),
                ('removed_by_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='removed_by_date')),
                ('time', models.BigIntegerField(verbose_name='time')),
                ('until', models.BigIntegerField(verbose_name='until')),
                ('template', models.PositiveSmallIntegerField(default=255, verbose_name='template')),
                ('server_scope', models.CharField(default=None, max_length=32, null=True, verbose_name='server_scope')),
                ('server_origin', models.CharField(default=None, max_length=32, null=True, verbose_name='server_origin')),
                ('silent', addons.models.MySQLBooleanField(null=True)),
                ('ipban', addons.models.MySQLBooleanField(null=True)),
                ('ipban_wildcard', addons.models.MySQLBooleanField(default=b'0', null=True)),
                ('active', addons.models.MySQLBooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Litebans_Mutes',
                'verbose_name_plural': 'Litebans_Mutes',
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('uuid', models.CharField(max_length=32, verbose_name='uuid')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'Litebans_Servers',
                'verbose_name_plural': 'Litebans_Servers',
            },
        ),
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.PositiveIntegerField(verbose_name='info')),
                ('msg', models.CharField(max_length=4096, verbose_name='msg')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
            ],
            options={
                'verbose_name': 'Litebans_Sync',
                'verbose_name_plural': 'Litebans_Sync',
            },
        ),
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=None, max_length=36, null=True, verbose_name='uuid')),
                ('ip', models.CharField(default=None, max_length=45, null=True, verbose_name='ip')),
                ('reason', models.CharField(default=None, max_length=2048, null=True, verbose_name='reason')),
                ('banned_by_uuid', models.CharField(max_length=36, verbose_name='banned_by_uuid')),
                ('banned_by_name', models.CharField(default=None, max_length=128, null=True, verbose_name='banned_by_name')),
                ('removed_by_uuid', models.CharField(default=None, max_length=36, null=True, verbose_name='removed_by_uuid')),
                ('removed_by_name', models.CharField(default=None, max_length=128, null=True, verbose_name='removed_by_name')),
                ('removed_by_reason', models.CharField(default=None, max_length=2048, null=True, verbose_name='removed_by_reason')),
                ('removed_by_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='removed_by_date')),
                ('time', models.BigIntegerField(verbose_name='time')),
                ('until', models.BigIntegerField(verbose_name='until')),
                ('template', models.PositiveSmallIntegerField(default=255, verbose_name='template')),
                ('server_scope', models.CharField(default=None, max_length=32, null=True, verbose_name='server_scope')),
                ('server_origin', models.CharField(default=None, max_length=32, null=True, verbose_name='server_origin')),
                ('silent', addons.models.MySQLBooleanField(null=True)),
                ('ipban', addons.models.MySQLBooleanField(null=True)),
                ('ipban_wildcard', addons.models.MySQLBooleanField(default=b'0', null=True)),
                ('active', addons.models.MySQLBooleanField(null=True)),
                ('warned', addons.models.MySQLBooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Litebans_Warnings',
                'verbose_name_plural': 'Litebans_Warnings',
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Ник игрока в вайтлисте')),
            ],
            options={
                'verbose_name': 'Ник игрока в вайтлисте',
                'verbose_name_plural': 'Ники игроков в вайтлисте',
            },
        ),
    ]
